### ISSUE TITLE
Reverse order of saferounding

### ISSUE THREAD

**Issue by 7k50** [cgdeboer/iteround#1]
Hi,

I am using saferound for a Pandas DataFrame column. Saferound seems to preferentially "award" the leftover sums to the first item in the array. I would like to reverse this order, "awarding" the leftover to the last item in the array, without reversing the order of the array (which I can't do because it can't be guaranteed that values in the array will always be so similar - they might be very different too - and I have a certain array order I wish to preserve in relation to other columns). Could that be possible?

`df["column"] = iteround.saferound(df["column"], 2)`

So instead of:

> 43.34 
> 43.33 
> 43.33 

it should be:

> 43.33 
> 43.33
> 43.34

**Comment by cgdeboer** [comment]
@winterflags, can you share the original array represented by `df["column"]` in your example ? 

`saferound` can accept a few different strategies for handling the leftovers (sum of orig vs sum of rounded). By default (per the README), the leftovers are awarded to items in the list in a way that reduces the change in items. By default, saferound use the DIFFERENCE strategy. That strategy seeks to minimize the absolute value of the sum of the deltas between each item's original value and the rounded value. It will adjust the items with the largest difference to preserve the sum. (See Fig 1, the arrow points to the value we are minimizing) 

##### Fig 1
![image](https://user-images.githubusercontent.com/174766/48301609-93d61480-e4be-11e8-940a-3268c01796bd.png)

If I'm not mistaken, you are looking for an additional `strategy` probably called `LAST`. Which awards the leftovers to (or from) the final value (based on the original order). Is that right ?

**Comment by cgdeboer** [comment]
@winterflags , thinking about the `LAST` methodology a bit more, which one of these outcomes best represents your use case.

Given `saferound(array, 0)` where array is represented by the `original` column below, does putting ALL the leftovers in the final item make more sense (**last_strategy_single** below adds 2 to item *d*), or does spreading the leftovers over last items make more sense (**last_strategy_spread** below adds 1 to items *c, d*). I'd bet spreading the difference out over as many last values as needed makes the most sense. You agree ?

![image](https://user-images.githubusercontent.com/174766/48301908-f5987d80-e4c2-11e8-828b-7e80660a84fc.png)

**Comment by 7k50** [comment]
@cgdeboer 

Sure – let's take this example of an original array:

`array = [676.333333333, 676.333333333, 676.333333333]`

The items are `<type 'float'>`, and have a long series of decimal numbers as they were generated via division (_2029/3_).

When running `array = iteround.saferound(array, 2)`, the array becomes:

`[676.34, 676.33, 676.33]`

Now, assuming that the array is part of a pandas DataFrame, I also have adjunct columns like this, and an additional value `1000` in the array:

```
+---------+---------+---------+
| index   | A       | array   |
|---------+---------+---------+
| 0       | first   | 1000    |
| 1       | second  | 676.34  |
| 2       | third   | 676.33  |
| 3       | last    | 676.33  |
+---------+---------+---------+
```

Here, I would always like to associate the largest saferounded number (676.34) with `last`, which always will be created to be in the last row.

> (I would not be able to just reverse the order of the array, even if freezing the other columns, as that would disassociate the values from their labels (i.e. `1000` is no longer `first`):
> 
> ```
> +---------+---------+---------+
> | index   | A       | array   |
> |---------+---------+---------+
> | 0       | first   | 676.33  |
> | 1       | second  | 676.33  |
> | 2       | third   | 676.34  |
> | 3       | last    | 1000    |
> +---------+---------+---------+
> ```

So that could perhaps be accomplished with a `LAST` strategy, which only awards leftover to a certain designated saferounded items, but is agnostic of other items in the array.

```
+---------+---------+---------+
| index   | A       | array   |
|---------+---------+---------+
| 0       | first   | 1000    |
| 1       | second  | 676.33  |
| 2       | third   | 676.33  |
| 3       | last    | 676.34  |
+---------+---------+---------+
```

Whether or not that's a viable strategy or request for `iteround`, I'm not in the position to say. Maybe a more flexible strategy implementation – if any – would be to somehow be able to assign which arbitrary index item in the array which should be awarded the leftovers, like [3] in this case (not too sure).

Regarding your second post, that's a very good question. I'd say for my specific use case, I would prefer **last_strategy_single** because I know that I always want to award the last item the remainder. Not because it's the most "equitable" solution, but because that particular item is the designated "fall guy". But that might be unusual, if so then maybe **last_strategy_spread** is more applicable to other people. But for me, it would not be much different from the default `DIFFERENCE`, although in reverse.

**Comment by cgdeboer** [comment]
Thanks for clarifying. In your use case, lets acknowledge that **spread** and **single** yield the same result. Each will increment the last item by `0.01`. Do you imagine that would always be the case ?

Furthermore, In your case above, the floats are all equal, which is a case I didn't think a lot about, but probably should have. When all the differences between the original and the rounded are the same, it seems to default to the first item to have a difference. (i.e the `1000` doesn't have a difference).

I've stubbed out a `LAST` and `FIRST` methodology, that addresses your use case above. 

```
In [16]: saferound([1000.0, 2029/3., 2029/3., 2029/3.], 2, strategy=LAST)
Out[16]: [1000.0, 676.33, 676.33, 676.34]
``` 

I'll need to write a test for it, add to documentation, then push up to pypi. Probably in the next few days. That sound ok ?

**Comment by 7k50** [comment]
> Thanks for clarifying. In your use case, lets acknowledge that **spread** and **single** yield the same result. Each will increment the last item by `0.01`. Do you imagine that would always be the case?

No, I don't think that always will be the case. I've seen examples of my program (with other numeric values) incrementing up more than one value, for instance the first and second while flooring the third. Again, for my particular use case, it would be better to award the last item the whole remainder while flooring the others. But I can see how that may of course be a bit counter-intuitive to what the purpose of saferound is, because I guess it increase the relative difference between the last item and the others.

> I've stubbed out a `LAST` and `FIRST` methodology, that addresses your use case above.
> 
> ```
> In [16]: saferound([1000.0, 2029/3., 2029/3., 2029/3.], 2, strategy=LAST)
> Out[16]: [1000.0, 676.33, 676.33, 676.34]
> ```
> I'll need to write a test for it, add to documentation, then push up to pypi. Probably in the next few days. That sound ok ?

That sounds fantastic, more than I would have hoped for. Thanks a lot!

**Comment by cgdeboer** [comment]
I think the logic you are looking for is actually pretty simple and may make more sense for you to have outside of this repository. Consider `df` is the following  Dataframe (same as example above):
```
In [55]: df
Out[55]:
        A        array
0   first  1000.000000
1  second   676.333333
2   third   676.333333
3    last   676.333333
```

You could accomplish your goal with something like these two lines, replacing the series values in your DataFrame with the rounded one.

```python
rounded = df.array.round(2).values
rounded[-1] += round(df.array.sum(), 2) - rounded.sum()
df['array'] = rounded
```
Let me know if that makes sense. It's possible I've oversimplified your case, but this seems like it would do what you are looking to do.

**Comment by 7k50** [comment]
> I think the logic you are looking for is actually pretty simple and may make more sense for you to have outside of this repository. Consider `df` is the following Dataframe (same as example above):
> 
> ```
> In [55]: df
> Out[55]:
>         A        array
> 0   first  1000.000000
> 1  second   676.333333
> 2   third   676.333333
> 3    last   676.333333
> ```
> You could accomplish your goal with something like these two lines, replacing the series values in your DataFrame with the rounded one.
> 
> ```python
> rounded = df.array.round(2).values
> rounded[-1] += round(df.array.sum(), 2) - rounded.sum()
> df['array'] = rounded
> ```
> 
> Let me know if that makes sense. It's possible I've oversimplified your case, but this seems like it would do what you are looking to do.

Yes, that seems to have worked, although I must admit I'm not entirely understanding of the logic/syntax just yet. I do understand that my use case is probably outside the scope of the module. Thanks a lot either way!

**Comment by cgdeboer** [comment]
@winterflags I'm going to go ahead and close this issue for now. If others have the same use case, then I'm happy to re-open and address the logic above. Good luck with your issue. Here's an annotation of the solution I posted above, perhaps it will help:

```python
# round all the items in the "array" column and return an numpy array of the values. calling .round() on an np.array or pandas.Series rounds each item, values returns as a numpy array.
rounded = df.array.round(2).values

# find and apply the difference of the following to values:
#    First, sum the total of the unrounded "array" column, and round its total to 2 places.
#    Second, sum the already rounded numbers.
# the difference in these two gives you the leftover (or deficit) that you need to adjust the final value by. We apply that different to the last value in the rounded array (i.e the last value is indexed by -1)
rounded[-1] += round(df.array.sum(), 2) - rounded.sum()

# set the "array" column to the original.
df['array'] = rounded
```

> You could even generalize that into a re-useable method in your application, like so.
```python
def winterflagsround(array, places):
    rounded = array.round(places).values
    rounded[-1] += round(array.sum(), places) - rounded.sum()
    return rounded
```

> And reuse like so
```python
df["column"] = winterflagsround(df["column"], 2)
```

Happy coding.
