### ISSUE TITLE
It's now on conda!

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [cgdeboer/iteround#3]
Just a little notification that a while back I took the liberty of adding iteround on conda-forge. Oppurtunity to add another badge to the README :wink: 

[![Conda Version](https://img.shields.io/conda/vn/conda-forge/iteround.svg)](https://anaconda.org/conda-forge/iteround)

**Comment by cgdeboer** [comment]
Thanks @Maarten-vd-Sande ... missed the notification on this one. I'll badge it up later this week 😄
