### ISSUE TITLE
Deadlock with empty list and non-zero `topline`

### ISSUE THREAD

**Issue by hoangphucITJP** [cgdeboer/iteround#4]
Running this line will result in deadlock:
```
a = 1 # Any number that is not zero
iteround.saferound([], 0, topline=a)
```
It would be nice if it raises an exception instead.

**Comment by cgdeboer** [comment]
@hoangphucITJP nice catch, will get that updated this week and push a fresh version.

**Comment by cgdeboer** [comment]
Resolve with `v1.0.4` https://pypi.org/project/iteround/1.0.4/
